-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2015 Statoil

SWOF
--	Sw	Krw	Kro	Pc						
	0.000000	0.000000	1.00000		0.000
	1.00000		1.000000	0.000000	0.000
/
SGOF
--#NAME?	Krg	Kro	Pc
	0.000000	0.000000	1.00000		0.000000
	1.00000		0.950000	0.000000	0.000000
/